import os
DIRECTORY = os.getcwd()

KI_ID = "ckgudcjf"
KI_URL_PRACTICE = 'https://openapi.koreainvestment.com:9443'
KI_ACCOUNT_PRACTICE = '19213095-01'
KI_ACCOUNT_PRACTICE_C = '19213095'
KI_APPKEY_PRACTICE = 'PSqpOrOHRPrKgJPfWF1k4SfLpIkCBa883RkB'
KI_APPSECRET_PRACTICE = 'svoYjp4GqG+je/F0JjH4ENn+hLm7JRU4yACQjEQgTznn5BK4KqoheaYWVbi71kj9mWOLcTCk4M5lpa4ESSL13CUGeBNclYLB7dAcYAndVd92DrQlZIgk5WP9h5vvLtXkcRA5h31XuwpWV5EQYBcY1xX0pnXSODev7Q+TCbwK3SMmdxaXR9k='

KI_URL_IMITATION = 'https://openapivts.koreainvestment.com:29443'
KI_ACCOUNT_IMITATION = '50081061-01'
KI_ACCOUNT_IMITATION_C = '50081061'
KI_APPKEY_IMITATION = 'PSgFaLpCMY9CLFFUCaguWyDVdnOwnfYNQSPs'
KI_APPSECRET_IMITATION = 'FfxV9JO+iOSy+OiwyPl3Yh+UM7koPNcv0z6X6omA7w+0CCz7WSUtcMU+zz9ZL7P73YOGq8sVyr6UgII+R8lfczwTVcXeb0WQQUEB7/D1rz9TrH13vVjCVA8ciTBGi+QDj+bV4r5HJBJBZpgzRbCALs6D3XsC+4QXuwkT/leKBQTbROWqobU='

LINE_URL = 'https://notify-api.line.me/api/notify'
LINE_TOKEN = '48zl8RmuB0lZoPOoVmqowZzjsUE0P53JO7jfVFCyLwh'

FILE_URL = DIRECTORY + '/_data'
FILE_URL_BACK = DIRECTORY + '/_back_10m/'
FILE_URL_BACKTEST = DIRECTORY + '/BacktestResult/'
FILE_URL_QUANT_TOTAL = FILE_URL + '/QuantData.xlsx'
FILE_URL_DATA_10M = FILE_URL + '/BotData_10m.xlsx'
FILE_URL_DATA_BACK_10M = FILE_URL + '/BotData_10m_backup.xlsx'
FILE_URL_QUANT_LIST_10M = FILE_URL + '/QuantDataList_10m.pickle'
FILE_URL_QUANT_RANK_10M = FILE_URL + '/QuantDataRank_10m.xlsx'
FILE_URL_QUANT_LAST_10M = FILE_URL + '/QuantLast_10m.pickle'
FILE_URL_BALANCE_LIST_10M = FILE_URL + '/BalanceList_10m.pickle'
FILE_URL_BALANCE_LIST_TEST_10M = FILE_URL_BACKTEST + '/BalanceListTest_10m.pickle'